ARG GO_VERSION
FROM golang:${GO_VERSION}-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -trimpath -o korpus ./cmd/korpus

FROM gcr.io/distroless/static:nonroot
COPY --from=builder /app/korpus /korpus
ENTRYPOINT ["/korpus"]
