// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetDiff implements GetDiff operation.
	//
	// GET /api/diff
	GetDiff(ctx context.Context, params GetDiffParams) (GetDiffRes, error)
	// GetHistory implements GetHistory operation.
	//
	// GET /api/history
	GetHistory(ctx context.Context, params GetHistoryParams) (*HistoryPage, error)
	// GetResource implements GetResource operation.
	//
	// GET /api/resource
	GetResource(ctx context.Context, params GetResourceParams) (GetResourceRes, error)
	// GetSnapshot implements GetSnapshot operation.
	//
	// GET /api/snapshot
	GetSnapshot(ctx context.Context, params GetSnapshotParams) (GetSnapshotRes, error)
	// GetStatus implements GetStatus operation.
	//
	// GET /api/status
	GetStatus(ctx context.Context) (*StatusResponse, error)
	// GetVolatility implements GetVolatility operation.
	//
	// GET /api/volatility
	GetVolatility(ctx context.Context, params GetVolatilityParams) (*VolatilityPage, error)
	// GetVolatilityFields implements GetVolatilityFields operation.
	//
	// GET /api/volatility/fields
	GetVolatilityFields(ctx context.Context, params GetVolatilityFieldsParams) (GetVolatilityFieldsRes, error)
	// Healthz implements Healthz operation.
	//
	// GET /healthz
	Healthz(ctx context.Context) (HealthzRes, error)
	// ListClusters implements ListClusters operation.
	//
	// GET /api/clusters
	ListClusters(ctx context.Context) ([]string, error)
	// ListGVKs implements ListGVKs operation.
	//
	// GET /api/gvks
	ListGVKs(ctx context.Context, params ListGVKsParams) ([]GVKInfo, error)
	// ListNamespaces implements ListNamespaces operation.
	//
	// GET /api/namespaces
	ListNamespaces(ctx context.Context, params ListNamespacesParams) ([]string, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
