// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetResource implements GetResource operation.
	//
	// GET /api/resources/{cluster}/{kind}/{namespace}/{name}
	GetResource(ctx context.Context, params GetResourceParams) (GetResourceRes, error)
	// GetResourceDiff implements GetResourceDiff operation.
	//
	// GET /api/resources/{cluster}/{kind}/{namespace}/{name}/diff
	GetResourceDiff(ctx context.Context, params GetResourceDiffParams) (GetResourceDiffRes, error)
	// GetResourceHistory implements GetResourceHistory operation.
	//
	// GET /api/resources/{cluster}/{kind}/{namespace}/{name}/history
	GetResourceHistory(ctx context.Context, params GetResourceHistoryParams) (GetResourceHistoryRes, error)
	// GetStatus implements GetStatus operation.
	//
	// GET /api/status
	GetStatus(ctx context.Context) (*StatusResponse, error)
	// Healthz implements Healthz operation.
	//
	// GET /healthz
	Healthz(ctx context.Context) (HealthzRes, error)
	// ListClusters implements ListClusters operation.
	//
	// GET /api/clusters
	ListClusters(ctx context.Context) ([]string, error)
	// ListKinds implements ListKinds operation.
	//
	// GET /api/kinds
	ListKinds(ctx context.Context, params ListKindsParams) ([]string, error)
	// ListNamespaces implements ListNamespaces operation.
	//
	// GET /api/namespaces
	ListNamespaces(ctx context.Context, params ListNamespacesParams) ([]string, error)
	// ListResources implements ListResources operation.
	//
	// GET /api/resources
	ListResources(ctx context.Context, params ListResourcesParams) ([]ResourceMeta, error)
	// QueryResources implements QueryResources operation.
	//
	// GET /api/query
	QueryResources(ctx context.Context, params QueryResourcesParams) (QueryResourcesRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
