// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	GetResourceOperation        OperationName = "GetResource"
	GetResourceDiffOperation    OperationName = "GetResourceDiff"
	GetResourceHistoryOperation OperationName = "GetResourceHistory"
	GetStatusOperation          OperationName = "GetStatus"
	HealthzOperation            OperationName = "Healthz"
	ListClustersOperation       OperationName = "ListClusters"
	ListKindsOperation          OperationName = "ListKinds"
	ListNamespacesOperation     OperationName = "ListNamespaces"
	ListResourcesOperation      OperationName = "ListResources"
	QueryResourcesOperation     OperationName = "QueryResources"
)
