// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetChurnParams is parameters of GetChurn operation.
type GetChurnParams struct {
	Cluster   OptString  `json:",omitempty,omitzero"`
	N         OptInt     `json:",omitempty,omitzero"`
	Threshold OptFloat64 `json:",omitempty,omitzero"`
}

func unpackGetChurnParams(packed middleware.Parameters) (params GetChurnParams) {
	{
		key := middleware.ParameterKey{
			Name: "cluster",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Cluster = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "n",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.N = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "threshold",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Threshold = v.(OptFloat64)
		}
	}
	return params
}

func decodeGetChurnParams(args [0]string, argsEscaped bool, r *http.Request) (params GetChurnParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: cluster.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "cluster",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotClusterVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotClusterVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Cluster.SetTo(paramsDotClusterVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cluster",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: n.
	{
		val := int(50)
		params.N.SetTo(val)
	}
	// Decode query: n.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "n",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotNVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotNVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.N.SetTo(paramsDotNVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "n",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: threshold.
	{
		val := float64(0.5)
		params.Threshold.SetTo(val)
	}
	// Decode query: threshold.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "threshold",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotThresholdVal float64
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToFloat64(val)
					if err != nil {
						return err
					}

					paramsDotThresholdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Threshold.SetTo(paramsDotThresholdVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Threshold.Get(); ok {
					if err := func() error {
						if err := (validate.Float{}).Validate(float64(value)); err != nil {
							return errors.Wrap(err, "float")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "threshold",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetResourceParams is parameters of GetResource operation.
type GetResourceParams struct {
	Cluster   string
	Kind      string
	Namespace string
	Name      string
}

func unpackGetResourceParams(packed middleware.Parameters) (params GetResourceParams) {
	{
		key := middleware.ParameterKey{
			Name: "cluster",
			In:   "path",
		}
		params.Cluster = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "kind",
			In:   "path",
		}
		params.Kind = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "namespace",
			In:   "path",
		}
		params.Namespace = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "name",
			In:   "path",
		}
		params.Name = packed[key].(string)
	}
	return params
}

func decodeGetResourceParams(args [4]string, argsEscaped bool, r *http.Request) (params GetResourceParams, _ error) {
	// Decode path: cluster.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "cluster",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Cluster = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cluster",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: kind.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "kind",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Kind = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "kind",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: namespace.
	if err := func() error {
		param := args[2]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[2])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "namespace",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Namespace = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "namespace",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: name.
	if err := func() error {
		param := args[3]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[3])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "name",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Name = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "name",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetResourceDiffParams is parameters of GetResourceDiff operation.
type GetResourceDiffParams struct {
	Cluster   string
	Kind      string
	Namespace string
	Name      string
	From      string
	To        string
}

func unpackGetResourceDiffParams(packed middleware.Parameters) (params GetResourceDiffParams) {
	{
		key := middleware.ParameterKey{
			Name: "cluster",
			In:   "path",
		}
		params.Cluster = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "kind",
			In:   "path",
		}
		params.Kind = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "namespace",
			In:   "path",
		}
		params.Namespace = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "name",
			In:   "path",
		}
		params.Name = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "from",
			In:   "query",
		}
		params.From = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "to",
			In:   "query",
		}
		params.To = packed[key].(string)
	}
	return params
}

func decodeGetResourceDiffParams(args [4]string, argsEscaped bool, r *http.Request) (params GetResourceDiffParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: cluster.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "cluster",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Cluster = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cluster",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: kind.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "kind",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Kind = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "kind",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: namespace.
	if err := func() error {
		param := args[2]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[2])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "namespace",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Namespace = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "namespace",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: name.
	if err := func() error {
		param := args[3]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[3])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "name",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Name = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "name",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: from.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "from",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.From = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "from",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: to.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "to",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.To = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "to",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetResourceHistoryParams is parameters of GetResourceHistory operation.
type GetResourceHistoryParams struct {
	Cluster   string
	Kind      string
	Namespace string
	Name      string
	N         OptInt `json:",omitempty,omitzero"`
}

func unpackGetResourceHistoryParams(packed middleware.Parameters) (params GetResourceHistoryParams) {
	{
		key := middleware.ParameterKey{
			Name: "cluster",
			In:   "path",
		}
		params.Cluster = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "kind",
			In:   "path",
		}
		params.Kind = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "namespace",
			In:   "path",
		}
		params.Namespace = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "name",
			In:   "path",
		}
		params.Name = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "n",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.N = v.(OptInt)
		}
	}
	return params
}

func decodeGetResourceHistoryParams(args [4]string, argsEscaped bool, r *http.Request) (params GetResourceHistoryParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: cluster.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "cluster",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Cluster = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cluster",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: kind.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "kind",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Kind = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "kind",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: namespace.
	if err := func() error {
		param := args[2]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[2])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "namespace",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Namespace = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "namespace",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: name.
	if err := func() error {
		param := args[3]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[3])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "name",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Name = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "name",
			In:   "path",
			Err:  err,
		}
	}
	// Set default value for query: n.
	{
		val := int(20)
		params.N.SetTo(val)
	}
	// Decode query: n.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "n",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotNVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotNVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.N.SetTo(paramsDotNVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "n",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// ListKindsParams is parameters of ListKinds operation.
type ListKindsParams struct {
	Cluster   OptString `json:",omitempty,omitzero"`
	Namespace OptString `json:",omitempty,omitzero"`
}

func unpackListKindsParams(packed middleware.Parameters) (params ListKindsParams) {
	{
		key := middleware.ParameterKey{
			Name: "cluster",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Cluster = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "namespace",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Namespace = v.(OptString)
		}
	}
	return params
}

func decodeListKindsParams(args [0]string, argsEscaped bool, r *http.Request) (params ListKindsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: cluster.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "cluster",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotClusterVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotClusterVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Cluster.SetTo(paramsDotClusterVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cluster",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: namespace.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "namespace",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotNamespaceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotNamespaceVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Namespace.SetTo(paramsDotNamespaceVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "namespace",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// ListNamespacesParams is parameters of ListNamespaces operation.
type ListNamespacesParams struct {
	Cluster OptString `json:",omitempty,omitzero"`
}

func unpackListNamespacesParams(packed middleware.Parameters) (params ListNamespacesParams) {
	{
		key := middleware.ParameterKey{
			Name: "cluster",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Cluster = v.(OptString)
		}
	}
	return params
}

func decodeListNamespacesParams(args [0]string, argsEscaped bool, r *http.Request) (params ListNamespacesParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: cluster.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "cluster",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotClusterVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotClusterVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Cluster.SetTo(paramsDotClusterVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cluster",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// ListResourcesParams is parameters of ListResources operation.
type ListResourcesParams struct {
	Cluster   OptString `json:",omitempty,omitzero"`
	Kind      OptString `json:",omitempty,omitzero"`
	Namespace OptString `json:",omitempty,omitzero"`
	Labels    OptString `json:",omitempty,omitzero"`
	Offset    OptInt    `json:",omitempty,omitzero"`
	Limit     OptInt    `json:",omitempty,omitzero"`
}

func unpackListResourcesParams(packed middleware.Parameters) (params ListResourcesParams) {
	{
		key := middleware.ParameterKey{
			Name: "cluster",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Cluster = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "kind",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Kind = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "namespace",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Namespace = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "labels",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Labels = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "offset",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Offset = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptInt)
		}
	}
	return params
}

func decodeListResourcesParams(args [0]string, argsEscaped bool, r *http.Request) (params ListResourcesParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: cluster.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "cluster",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotClusterVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotClusterVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Cluster.SetTo(paramsDotClusterVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cluster",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: kind.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "kind",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotKindVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotKindVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Kind.SetTo(paramsDotKindVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "kind",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: namespace.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "namespace",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotNamespaceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotNamespaceVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Namespace.SetTo(paramsDotNamespaceVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "namespace",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: labels.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "labels",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLabelsVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotLabelsVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Labels.SetTo(paramsDotLabelsVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "labels",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: offset.
	{
		val := int(0)
		params.Offset.SetTo(val)
	}
	// Decode query: offset.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "offset",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotOffsetVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotOffsetVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Offset.SetTo(paramsDotOffsetVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "offset",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: limit.
	{
		val := int(50)
		params.Limit.SetTo(val)
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// QueryResourcesParams is parameters of QueryResources operation.
type QueryResourcesParams struct {
	Kind      string
	Namespace OptString `json:",omitempty,omitzero"`
	Cluster   OptString `json:",omitempty,omitzero"`
	Labels    OptString `json:",omitempty,omitzero"`
	Q         OptString `json:",omitempty,omitzero"`
	Offset    OptInt    `json:",omitempty,omitzero"`
	Limit     OptInt    `json:",omitempty,omitzero"`
}

func unpackQueryResourcesParams(packed middleware.Parameters) (params QueryResourcesParams) {
	{
		key := middleware.ParameterKey{
			Name: "kind",
			In:   "query",
		}
		params.Kind = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "namespace",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Namespace = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "cluster",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Cluster = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "labels",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Labels = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "q",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Q = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "offset",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Offset = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptInt)
		}
	}
	return params
}

func decodeQueryResourcesParams(args [0]string, argsEscaped bool, r *http.Request) (params QueryResourcesParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: kind.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "kind",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Kind = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "kind",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: namespace.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "namespace",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotNamespaceVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotNamespaceVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Namespace.SetTo(paramsDotNamespaceVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "namespace",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: cluster.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "cluster",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotClusterVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotClusterVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Cluster.SetTo(paramsDotClusterVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cluster",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: labels.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "labels",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLabelsVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotLabelsVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Labels.SetTo(paramsDotLabelsVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "labels",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: q.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "q",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotQVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotQVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Q.SetTo(paramsDotQVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "q",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: offset.
	{
		val := int(0)
		params.Offset.SetTo(val)
	}
	// Decode query: offset.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "offset",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotOffsetVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotOffsetVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Offset.SetTo(paramsDotOffsetVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "offset",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: limit.
	{
		val := int(50)
		params.Limit.SetTo(val)
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
