// Code generated by ogen, DO NOT EDIT.
package api

type GetDiffRes interface {
	getDiffRes()
}

type GetResourceRes interface {
	getResourceRes()
}

type GetSnapshotRes interface {
	getSnapshotRes()
}

type GetVolatilityFieldsRes interface {
	getVolatilityFieldsRes()
}

type HealthzRes interface {
	healthzRes()
}
