// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetDiff implements GetDiff operation.
//
// GET /api/diff
func (UnimplementedHandler) GetDiff(ctx context.Context, params GetDiffParams) (r GetDiffRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHistory implements GetHistory operation.
//
// GET /api/history
func (UnimplementedHandler) GetHistory(ctx context.Context, params GetHistoryParams) (r *HistoryPage, _ error) {
	return r, ht.ErrNotImplemented
}

// GetResource implements GetResource operation.
//
// GET /api/resource
func (UnimplementedHandler) GetResource(ctx context.Context, params GetResourceParams) (r GetResourceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSnapshot implements GetSnapshot operation.
//
// GET /api/snapshot
func (UnimplementedHandler) GetSnapshot(ctx context.Context, params GetSnapshotParams) (r GetSnapshotRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetStatus implements GetStatus operation.
//
// GET /api/status
func (UnimplementedHandler) GetStatus(ctx context.Context) (r *StatusResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// GetVolatility implements GetVolatility operation.
//
// GET /api/volatility
func (UnimplementedHandler) GetVolatility(ctx context.Context, params GetVolatilityParams) (r *VolatilityPage, _ error) {
	return r, ht.ErrNotImplemented
}

// GetVolatilityFields implements GetVolatilityFields operation.
//
// GET /api/volatility/fields
func (UnimplementedHandler) GetVolatilityFields(ctx context.Context, params GetVolatilityFieldsParams) (r GetVolatilityFieldsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Healthz implements Healthz operation.
//
// GET /healthz
func (UnimplementedHandler) Healthz(ctx context.Context) (r HealthzRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListClusters implements ListClusters operation.
//
// GET /api/clusters
func (UnimplementedHandler) ListClusters(ctx context.Context) (r []string, _ error) {
	return r, ht.ErrNotImplemented
}

// ListGVKs implements ListGVKs operation.
//
// GET /api/gvks
func (UnimplementedHandler) ListGVKs(ctx context.Context, params ListGVKsParams) (r []GVKInfo, _ error) {
	return r, ht.ErrNotImplemented
}

// ListNamespaces implements ListNamespaces operation.
//
// GET /api/namespaces
func (UnimplementedHandler) ListNamespaces(ctx context.Context, params ListNamespacesParams) (r []string, _ error) {
	return r, ht.ErrNotImplemented
}
