// Code generated by ogen, DO NOT EDIT.
package api

type GetResourceDiffRes interface {
	getResourceDiffRes()
}

type GetResourceHistoryRes interface {
	getResourceHistoryRes()
}

type GetResourceRes interface {
	getResourceRes()
}

type HealthzRes interface {
	healthzRes()
}

type QueryResourcesRes interface {
	queryResourcesRes()
}
