// Code generated by ogen, DO NOT EDIT.

package api

import (
	"io"
	"time"
)

// Ref: #/components/schemas/ClusterStatus
type ClusterStatus struct {
	Name          string         `json:"name"`
	LastPullAt    OptNilDateTime `json:"lastPullAt"`
	LastPullErr   string         `json:"lastPullErr"`
	ResourceCount int            `json:"resourceCount"`
}

// GetName returns the value of Name.
func (s *ClusterStatus) GetName() string {
	return s.Name
}

// GetLastPullAt returns the value of LastPullAt.
func (s *ClusterStatus) GetLastPullAt() OptNilDateTime {
	return s.LastPullAt
}

// GetLastPullErr returns the value of LastPullErr.
func (s *ClusterStatus) GetLastPullErr() string {
	return s.LastPullErr
}

// GetResourceCount returns the value of ResourceCount.
func (s *ClusterStatus) GetResourceCount() int {
	return s.ResourceCount
}

// SetName sets the value of Name.
func (s *ClusterStatus) SetName(val string) {
	s.Name = val
}

// SetLastPullAt sets the value of LastPullAt.
func (s *ClusterStatus) SetLastPullAt(val OptNilDateTime) {
	s.LastPullAt = val
}

// SetLastPullErr sets the value of LastPullErr.
func (s *ClusterStatus) SetLastPullErr(val string) {
	s.LastPullErr = val
}

// SetResourceCount sets the value of ResourceCount.
func (s *ClusterStatus) SetResourceCount(val int) {
	s.ResourceCount = val
}

// Ref: #/components/schemas/DiffResult
type DiffResult struct {
	Before string `json:"before"`
	After  string `json:"after"`
}

// GetBefore returns the value of Before.
func (s *DiffResult) GetBefore() string {
	return s.Before
}

// GetAfter returns the value of After.
func (s *DiffResult) GetAfter() string {
	return s.After
}

// SetBefore sets the value of Before.
func (s *DiffResult) SetBefore(val string) {
	s.Before = val
}

// SetAfter sets the value of After.
func (s *DiffResult) SetAfter(val string) {
	s.After = val
}

func (*DiffResult) getResourceDiffRes() {}

// GetResourceDiffBadRequest is response for GetResourceDiff operation.
type GetResourceDiffBadRequest struct{}

func (*GetResourceDiffBadRequest) getResourceDiffRes() {}

// GetResourceDiffNotFound is response for GetResourceDiff operation.
type GetResourceDiffNotFound struct{}

func (*GetResourceDiffNotFound) getResourceDiffRes() {}

// GetResourceHistoryNotFound is response for GetResourceHistory operation.
type GetResourceHistoryNotFound struct{}

func (*GetResourceHistoryNotFound) getResourceHistoryRes() {}

type GetResourceHistoryOKApplicationJSON []HistoryEntry

func (*GetResourceHistoryOKApplicationJSON) getResourceHistoryRes() {}

// GetResourceNotFound is response for GetResource operation.
type GetResourceNotFound struct{}

func (*GetResourceNotFound) getResourceRes() {}

type GetResourceOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetResourceOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetResourceOK) getResourceRes() {}

// HealthzOK is response for Healthz operation.
type HealthzOK struct{}

func (*HealthzOK) healthzRes() {}

// HealthzServiceUnavailable is response for Healthz operation.
type HealthzServiceUnavailable struct{}

func (*HealthzServiceUnavailable) healthzRes() {}

// Ref: #/components/schemas/HistoryEntry
type HistoryEntry struct {
	Sha       string    `json:"sha"`
	Timestamp time.Time `json:"timestamp"`
	Message   string    `json:"message"`
}

// GetSha returns the value of Sha.
func (s *HistoryEntry) GetSha() string {
	return s.Sha
}

// GetTimestamp returns the value of Timestamp.
func (s *HistoryEntry) GetTimestamp() time.Time {
	return s.Timestamp
}

// GetMessage returns the value of Message.
func (s *HistoryEntry) GetMessage() string {
	return s.Message
}

// SetSha sets the value of Sha.
func (s *HistoryEntry) SetSha(val string) {
	s.Sha = val
}

// SetTimestamp sets the value of Timestamp.
func (s *HistoryEntry) SetTimestamp(val time.Time) {
	s.Timestamp = val
}

// SetMessage sets the value of Message.
func (s *HistoryEntry) SetMessage(val string) {
	s.Message = val
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilDateTime returns new OptNilDateTime with value set to v.
func NewOptNilDateTime(v time.Time) OptNilDateTime {
	return OptNilDateTime{
		Value: v,
		Set:   true,
	}
}

// OptNilDateTime is optional nullable time.Time.
type OptNilDateTime struct {
	Value time.Time
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilDateTime was set.
func (o OptNilDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilDateTime) SetToNull() {
	o.Set = true
	o.Null = true
	var v time.Time
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilResourceMetaLabels returns new OptNilResourceMetaLabels with value set to v.
func NewOptNilResourceMetaLabels(v ResourceMetaLabels) OptNilResourceMetaLabels {
	return OptNilResourceMetaLabels{
		Value: v,
		Set:   true,
	}
}

// OptNilResourceMetaLabels is optional nullable ResourceMetaLabels.
type OptNilResourceMetaLabels struct {
	Value ResourceMetaLabels
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilResourceMetaLabels was set.
func (o OptNilResourceMetaLabels) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilResourceMetaLabels) Reset() {
	var v ResourceMetaLabels
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilResourceMetaLabels) SetTo(v ResourceMetaLabels) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilResourceMetaLabels) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilResourceMetaLabels) SetToNull() {
	o.Set = true
	o.Null = true
	var v ResourceMetaLabels
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilResourceMetaLabels) Get() (v ResourceMetaLabels, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilResourceMetaLabels) Or(d ResourceMetaLabels) ResourceMetaLabels {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// QueryResourcesBadRequest is response for QueryResources operation.
type QueryResourcesBadRequest struct{}

func (*QueryResourcesBadRequest) queryResourcesRes() {}

type QueryResourcesOKApplicationJSON []ResourceMeta

func (*QueryResourcesOKApplicationJSON) queryResourcesRes() {}

// Ref: #/components/schemas/ResourceMeta
type ResourceMeta struct {
	Cluster           string                   `json:"cluster"`
	Kind              string                   `json:"kind"`
	Name              string                   `json:"name"`
	Namespace         string                   `json:"namespace"`
	Labels            OptNilResourceMetaLabels `json:"labels"`
	CreationTimestamp OptString                `json:"creationTimestamp"`
}

// GetCluster returns the value of Cluster.
func (s *ResourceMeta) GetCluster() string {
	return s.Cluster
}

// GetKind returns the value of Kind.
func (s *ResourceMeta) GetKind() string {
	return s.Kind
}

// GetName returns the value of Name.
func (s *ResourceMeta) GetName() string {
	return s.Name
}

// GetNamespace returns the value of Namespace.
func (s *ResourceMeta) GetNamespace() string {
	return s.Namespace
}

// GetLabels returns the value of Labels.
func (s *ResourceMeta) GetLabels() OptNilResourceMetaLabels {
	return s.Labels
}

// GetCreationTimestamp returns the value of CreationTimestamp.
func (s *ResourceMeta) GetCreationTimestamp() OptString {
	return s.CreationTimestamp
}

// SetCluster sets the value of Cluster.
func (s *ResourceMeta) SetCluster(val string) {
	s.Cluster = val
}

// SetKind sets the value of Kind.
func (s *ResourceMeta) SetKind(val string) {
	s.Kind = val
}

// SetName sets the value of Name.
func (s *ResourceMeta) SetName(val string) {
	s.Name = val
}

// SetNamespace sets the value of Namespace.
func (s *ResourceMeta) SetNamespace(val string) {
	s.Namespace = val
}

// SetLabels sets the value of Labels.
func (s *ResourceMeta) SetLabels(val OptNilResourceMetaLabels) {
	s.Labels = val
}

// SetCreationTimestamp sets the value of CreationTimestamp.
func (s *ResourceMeta) SetCreationTimestamp(val OptString) {
	s.CreationTimestamp = val
}

type ResourceMetaLabels map[string]string

func (s *ResourceMetaLabels) init() ResourceMetaLabels {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/StatusResponse
type StatusResponse struct {
	Clusters []ClusterStatus `json:"clusters"`
}

// GetClusters returns the value of Clusters.
func (s *StatusResponse) GetClusters() []ClusterStatus {
	return s.Clusters
}

// SetClusters sets the value of Clusters.
func (s *StatusResponse) SetClusters(val []ClusterStatus) {
	s.Clusters = val
}
