// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/validate"
)

func (s GetResourceHistoryOKApplicationJSON) Validate() error {
	alias := ([]HistoryEntry)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s QueryResourcesOKApplicationJSON) Validate() error {
	alias := ([]ResourceMeta)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s *StatusResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Clusters == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "clusters",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}
