// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	GetDiffOperation             OperationName = "GetDiff"
	GetHistoryOperation          OperationName = "GetHistory"
	GetResourceOperation         OperationName = "GetResource"
	GetSnapshotOperation         OperationName = "GetSnapshot"
	GetStatusOperation           OperationName = "GetStatus"
	GetVolatilityOperation       OperationName = "GetVolatility"
	GetVolatilityFieldsOperation OperationName = "GetVolatilityFields"
	HealthzOperation             OperationName = "Healthz"
	ListClustersOperation        OperationName = "ListClusters"
	ListGVKsOperation            OperationName = "ListGVKs"
	ListNamespacesOperation      OperationName = "ListNamespaces"
)
