// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetChurn implements GetChurn operation.
//
// GET /api/churn
func (UnimplementedHandler) GetChurn(ctx context.Context, params GetChurnParams) (r []ChurnEntry, _ error) {
	return r, ht.ErrNotImplemented
}

// GetResource implements GetResource operation.
//
// GET /api/resources/{cluster}/{kind}/{namespace}/{name}
func (UnimplementedHandler) GetResource(ctx context.Context, params GetResourceParams) (r GetResourceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetResourceDiff implements GetResourceDiff operation.
//
// GET /api/resources/{cluster}/{kind}/{namespace}/{name}/diff
func (UnimplementedHandler) GetResourceDiff(ctx context.Context, params GetResourceDiffParams) (r GetResourceDiffRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetResourceHistory implements GetResourceHistory operation.
//
// GET /api/resources/{cluster}/{kind}/{namespace}/{name}/history
func (UnimplementedHandler) GetResourceHistory(ctx context.Context, params GetResourceHistoryParams) (r GetResourceHistoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetStatus implements GetStatus operation.
//
// GET /api/status
func (UnimplementedHandler) GetStatus(ctx context.Context) (r *StatusResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// Healthz implements Healthz operation.
//
// GET /healthz
func (UnimplementedHandler) Healthz(ctx context.Context) (r HealthzRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListClusters implements ListClusters operation.
//
// GET /api/clusters
func (UnimplementedHandler) ListClusters(ctx context.Context) (r []string, _ error) {
	return r, ht.ErrNotImplemented
}

// ListKinds implements ListKinds operation.
//
// GET /api/kinds
func (UnimplementedHandler) ListKinds(ctx context.Context, params ListKindsParams) (r []string, _ error) {
	return r, ht.ErrNotImplemented
}

// ListNamespaces implements ListNamespaces operation.
//
// GET /api/namespaces
func (UnimplementedHandler) ListNamespaces(ctx context.Context, params ListNamespacesParams) (r []string, _ error) {
	return r, ht.ErrNotImplemented
}

// ListResources implements ListResources operation.
//
// GET /api/resources
func (UnimplementedHandler) ListResources(ctx context.Context, params ListResourcesParams) (r *ResourceListPage, _ error) {
	return r, ht.ErrNotImplemented
}

// QueryResources implements QueryResources operation.
//
// GET /api/query
func (UnimplementedHandler) QueryResources(ctx context.Context, params QueryResourcesParams) (r QueryResourcesRes, _ error) {
	return r, ht.ErrNotImplemented
}
