name: Release

on:
  push:
    tags: ['v*.*.*']

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - name: Set image tags in manifests
        working-directory: manifests
        run: |
          kustomize edit set image ghcr.io/${{ github.repository }}=ghcr.io/${{ github.repository }}:release-${{ github.ref_name }}
          kustomize edit set image ghcr.io/${{ github.repository }}-server=ghcr.io/${{ github.repository }}-server:release-${{ github.ref_name }}

      - name: Build install.yaml
        run: kustomize build ./manifests > install.yaml

      - uses: softprops/action-gh-release@v3
        with:
          files: install.yaml
          generate_release_notes: true
